---
title: "Bioinformatics for Proteomics (classic course)"
date: 2026-06-01
description: "The original hands-on CompOmics course on mass spectrometry-based proteomics data analysis: identification, functional analysis, data sharing, and quantification. Slides and exercise resources included. A modernised version is in preparation."
categories: [proteomics, course, identification, quantification, data-sharing, searchgui, peptideshaker]
---

This is the classic **Bioinformatics for Proteomics** course, a hands-on introduction to mass spectrometry-based proteomics data analysis. It is organised into four modules covering peptide and protein identification, functional analysis, data sharing through public repositories, and quantification.

::: {.callout-note}
This page preserves the original course materials. Some tools, formats, and versions reflect the state of the field when the course was written and are now partly outdated (for example, PRIDE XML has been superseded by mzIdentML and mzTab). A modernised version is in preparation. Materials are shared under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/). If you use them, please cite [Vaudel et al. (2014), PMID 24678044](https://www.ncbi.nlm.nih.gov/pubmed/24678044).
:::

**General resources**

- [Questions and answers document](https://drive.google.com/file/d/0B4sW8rLWPbRyV1ZnaVZoaHktWlE/view?usp=sharing&resourcekey=0-nv0BLwLDq5qO-6YOgK49Ag)
- [Feedback form](https://docs.google.com/forms/d/1BQfRAZ1L4Szn_vsMaICiYyu84sKjXU8xQXFmwXg_oOI/viewform)

## 1. Identification

Complete workflow for peptide and protein identification from mass spectrometry data: raw data conversion, spectrum processing, database preparation, peptide-spectrum matching, peptide and protein inference, validation, PTM analysis, and de novo sequencing.

**1.1 Database generation**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyUGxQdmw3cGNUSTQ/view?usp=sharing&resourcekey=0-VIMx1s6vmKRwMOBkOlS6Ng)

**1.2 Peak list generation**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyYTJBZVZkZFFuSUE/view?usp=sharing&resourcekey=0-lctIbpXK4PN2uxwK7g13HQ)
- [Exercise resources](https://drive.google.com/file/d/1xhfAreX_PJzKscyLAuMfqYEJNZFkeAfP/view?usp=sharing)
- Tool: [ProteoWizard](http://proteowizard.sourceforge.net/)

**1.3 Peptide to spectrum matching**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyaDBXMDVXOWVaUkk/view?usp=sharing&resourcekey=0-4jJ7-2kjLBDci1eBytMO1A)
- [Exercise resources](https://drive.google.com/file/d/1q-1Wc865DZK8YQwGAXclTLFy8rBov2NJ/view?usp=sharing)
- Tool: [SearchGUI](http://compomics.github.io/projects/searchgui.html)

**1.4 Browsing identification results**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyUm5tdFRObTJSaEE/view?usp=sharing&resourcekey=0-NgNbCuD5h8MAoJy79cJk7w)
- [Exercise resources](https://drive.google.com/file/d/1cfatBwiQkchnKKsBvAfQ0BvfhgMBHnhA/view?usp=sharing)
- Tool: [PeptideShaker](http://compomics.github.io/projects/peptide-shaker.html)

**1.5 Peptide and protein validation**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyUU9ycjFScmlaZjA/view?usp=sharing&resourcekey=0-LLHCRH0CUf9Xzx7BlITSPQ)
- Tool: [PeptideShaker](http://compomics.github.io/projects/peptide-shaker.html)

**1.6 PTM analysis**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRybHZXeVBvNXB1Tkk/view?usp=sharing&resourcekey=0-C4_nR2G5vhwRpESsONlFMQ)
- [Exercise resources](https://drive.google.com/file/d/1j-6zj_g5jZFT8ywrYYsN8zuS4x4lXMYS/view?usp=sharing)
- Tool: [PeptideShaker](http://compomics.github.io/projects/peptide-shaker.html) ([download 3.0.11](https://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/3.0.11/PeptideShaker-3.0.11.zip))

**1.7 De novo peptide identification**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRySWhqTGUtS1hVRGs/view?usp=sharing&resourcekey=0-Hplewb7eyWoIgCK5kzKvfw)
- [Exercise resources](https://drive.google.com/file/d/1L0Se_afHDL0G8AbAq9KOJQrr-aQX9gUn/view?usp=sharing)
- Tool: [DeNovoGUI](http://compomics.github.io/projects/denovogui.html)

## 2. Functional analysis

Extracting biological meaning from identification results: retrieving additional protein information, pathway analysis, 3D structure visualisation, and Gene Ontology annotation.

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRybzZKMHJxR04tVkU/view?usp=sharing&resourcekey=0--IhNfNOJsvEHBAEhGPzX0A)
- [Exercise resources](https://drive.google.com/file/d/12V_5RpVdpXODrLxPR2eT89LJvcZF34r5/view?usp=sharing)

## 3. Data sharing

Submission and reuse of proteomics data through community repositories: converting results to standard formats, submitting to PRIDE and ProteomeXchange, browsing published datasets, and reprocessing existing data.

::: {.callout-note}
The slides in this module refer to PRIDE XML, which has since been deprecated. Current submissions use [mzIdentML](https://www.psidev.info/mzidentml) and [mzTab](https://www.psidev.info/mztab); the overall submission workflow through PRIDE and ProteomeXchange is otherwise unchanged.
:::

**3.0 Introduction**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyb3BHYWtud2tCTkE/view?usp=sharing&resourcekey=0-LKTuwWEKerk6fh62BXTonA)

**3.1 Submit**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyeW80cHptYnhxSmc/view?usp=sharing&resourcekey=0-twqVpJPMU2_Z19tHpf9QGQ)
- [Exercise resources](https://drive.google.com/file/d/1AxIcN_uP7UONJFYrserKxma6tOPO-kk5/view?usp=sharing)

**3.2 Browse**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRydkxfTEJJSDNDeG8/view?usp=sharing&resourcekey=0-fnyQy8iK8H4BC5JOwP-JJw)
- [Exercise resources](https://drive.google.com/file/d/1ncT57QBr6Z4vMSRHFsgPLAA1S04S4f1L/view?usp=sharing)

**3.3 Reprocess**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRydjFLSHR2UUZXbWM/view?usp=sharing&resourcekey=0-RA3FRAGW1f3LDlxmiulJZQ)

**Repositories and tools:** [ProteomeXchange](http://www.proteomexchange.org/), [PRIDE](http://www.ebi.ac.uk/pride), [PRIDE Inspector](https://github.com/PRIDE-Toolsuite/pride-inspector)

## 4. Quantification

Protein abundance estimation across several orders of magnitude in concentration, covering the main quantification strategies and their trade-offs.

**4.0 Introduction**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyRkw3dzRaRWkzSGc/view?usp=sharing&resourcekey=0-LuG7ussiMG8NsPcwJfY-xw)

**4.1 Spectrum counting**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyYXJLTDZxd3IyTTA/view?usp=sharing&resourcekey=0-m-E3assyzNcxDq6J2BO5Dw)
- Tool: [PeptideShaker](http://compomics.github.io/projects/peptide-shaker.html)

**4.2 Reporter ions**

- [Slides](https://drive.google.com/file/d/0B4sW8rLWPbRyZ3RBZHBpcm5jWnc/view?usp=sharing&resourcekey=0-SfjWCN2oh3tlKauVAh-Hgg)
- [Exercise resources](https://drive.google.com/file/d/1ld991SYLJJZisOdQEaSCsTtop-_oKywO/view?usp=sharing)
- Tools: [SearchGUI](http://compomics.github.io/projects/searchgui.html), [PeptideShaker](http://compomics.github.io/projects/peptide-shaker.html), [Reporter](http://compomics.github.io/projects/reporter.html)

**4.5 Statistical analysis**

- [Slides](https://drive.google.com/file/d/0B4hBxjyTLNhiM0xaR3Q2MklHdUk/view?usp=sharing&resourcekey=0-2Xj8wosJgwTAojqsPIhLIg)
- [Exercise resources](https://drive.google.com/file/d/1KUTY4mMVd74YrNrpIjlf8kAYr8crTTzu/view?usp=sharing)
- Tool: [Perseus](http://coxdocs.org/doku.php?id=perseus:start)
